const isDevelopment = __DEV__;

const APIURL = isDevelopment ? 'apis/dev/actions.php' : 'apis/prod/actions.php';
const INSIGHTSAPI = isDevelopment ? 'apis/dev/userInsights.php' : 'apis/prod/userInsights.php';
const UTILS_ACTIONS_API_URL = isDevelopment ? 'apis/dev/utilsActions.php' : 'apis/prod/utilsActions.php';
const SOCIAL_API_URL = isDevelopment ? 'apis/dev/social/social-api.php' : 'apis/prod/social/social-api.php';
const CHALLENGES_API_URL = isDevelopment ? 'apis/dev/challenges/challenges-api.php' : 'apis/prod/challenges/challenges-api.php';

const requests = {
    //request to biblophile actions api
    getBookGenre:`${APIURL}?action=getBookGenre`,
    getBooks:`${APIURL}?action=getBooks&bookGenre=`,
    getSpotlight: `${APIURL}?action=getSpotlight`,
    fetchProductDetails:`${APIURL}?action=fetchProductDetails&id=`,
    fetchExternalBookDetails:`${APIURL}?action=fetchExternalBookDetails&id=`, 
    fetchAverageRating:`${APIURL}?action=fetchAverageRating&id=`,
    fetchAverageEmotions:`${APIURL}?action=fetchAverageEmotions&id=`,
    addBook: `${APIURL}?action=addBook`,
    submitBookRequest: `${APIURL}?action=submitBookRequest`,
    fetchBookId:`${APIURL}?action=fetchBookId`,
    fetchReadingStatus:`${APIURL}?action=fetchReadingStatus`,
    submitReadingStatus: `${APIURL}?action=submitReadingStatus`,
    submitReadingDuration: `${APIURL}?action=submitReadingDuration`,
    fetchProductReviews:`${APIURL}?action=fetchProductReviews&id=`,
    fetchEmotions:`${APIURL}?action=fetchEmotions`,
    submitReview: `${APIURL}?action=submitReview`,
    submitNote: `${APIURL}?action=submitNote`,
    submitEmotionScore: `${APIURL}?action=submitEmotionScore`,
    placeOrder: `${APIURL}?action=placeOrder`,
    placeSubscriptionOrder: `${APIURL}?action=placeSubscriptionOrder`,
    userLogin: `${APIURL}?action=userLogin`,
    userLogout: `${APIURL}?action=logout`,
    userSignup: `${APIURL}?action=userSignup`,
    forgotPassword: `${APIURL}?action=forgotPassword`,
    fetchUserData: `${APIURL}?action=fetchUserData`,
    fetchUserDataFromUsername: `${APIURL}?action=fetchUserDataFromUsername`,
    fetchOrders: `${APIURL}?action=fetchOrders`,
    updateUserData: `${APIURL}?action=updateUserData`,
    updateAppUserData: `${APIURL}?action=updateAppUserData`,
    fetchDeposit: `${APIURL}?action=fetchDeposit`,
    searchBooks: `${APIURL}?action=searchBooks&searchQuery=`,
    searchExternalBooks: `${APIURL}?action=searchExternalBooks&searchQuery=`,
    fetchSeasonalRecommendations: `${APIURL}?action=fetchSeasonalRecommendations`,
    fetchHotRecommendations: `${APIURL}?action=fetchHotRecommendations`,
    fetchCulturalRecommendations: `${APIURL}?action=fetchCulturalRecommendations`,
    fetchGiveawayBooks: `${APIURL}?action=fetchGiveawayBooks`,
    fetchSubscriptionPlans: `${APIURL}?action=fetchSubscriptionPlans`,
    fetchActivePlan: `${APIURL}?action=fetchActivePlan&userId=`,
    getBookmarks: `${APIURL}?action=getBookmarks`,
    fetchReadingStreak: `${APIURL}?action=fetchReadingStreak&userId=`,
    fetchReadingStreakLogs: `${APIURL}?action=fetchReadingStreakLogs`,
    updateReadingStreak: `${APIURL}?action=updateReadingStreak&userId=`,
    updatePagesRead: `${APIURL}?action=updatePagesRead`,
    fetchReadingTips: `${APIURL}?action=fetchReadingTips`,
    registerNotificationToken: `${APIURL}?action=registerNotificationToken`,
    fetchReadingStreakLeaderboard: `${APIURL}?action=fetchReadingStreakLeaderboard&userId=`,
    fetchPagesRead: `${APIURL}?action=fetchPagesRead&userId=`,
    fetchReadingDurationGraph: `${APIURL}?action=fetchReadingDurationGraph&userId=`,
    fetchCurrentReads: `${APIURL}?action=fetchCurrentReads`,
    fetchUserBooks: `${APIURL}?action=fetchUserBooks`,
    updateBookDates: `${APIURL}?action=updateBookDates`,
    paymentRequest: `${APIURL}?action=paymentRequest`,
    paymentSuccessful: `${APIURL}?action=paymentSuccessful&linkId=`,

    //request to biblophile user-insights api
    fetchAverageRatingByUser:`${INSIGHTSAPI}?action=fetchAverageRatingByUser&userId=`,
    fetchAverageEmotionsByUser:`${INSIGHTSAPI}?action=fetchAverageEmotionsByUser&userId=`,
    fetchAverageDaystoFinish: `${INSIGHTSAPI}?action=fetchAverageDaystoFinish&userId=`,
    fetchUserReviews: `${INSIGHTSAPI}?action=fetchUserReviews&userId=`,
    updateUserReview: `${INSIGHTSAPI}?action=updateUserReview`,
    fetchBookShelf: `${INSIGHTSAPI}?action=fetchBookShelf`,
    fetchUserNotes: `${INSIGHTSAPI}?action=fetchUserNotes&userId=`,
    updateUserNote: `${INSIGHTSAPI}?action=updateUserNote`,
    fetchReadingDurations: `${INSIGHTSAPI}?action=fetchReadingDurations&userId=`,
    fetchUserGoals: `${INSIGHTSAPI}?action=fetchUserGoals&userId=`,
    fetchCurrentProgress: `${INSIGHTSAPI}?action=fetchCurrentProgress&userId=`,
    submitGoal: `${INSIGHTSAPI}?action=submitGoal&userId=`,

    //request to biblophile util apis
    fetchBannerData:`${UTILS_ACTIONS_API_URL}?action=fetchBannerData`,

    //request to biblophile social apis
    fetchUserRelations:`${SOCIAL_API_URL}?action=fetchUserRelations`,
    fetchFriendRequests:`${SOCIAL_API_URL}?action=fetchFriendRequests`,
    toggleFollow:`${SOCIAL_API_URL}?action=toggleFollow`,
    toggleFriend:`${SOCIAL_API_URL}?action=toggleFriend`,
    confirmRejectFriend:`${SOCIAL_API_URL}?action=confirmRejectFriend`,
    fetchPrivacyStatus:`${SOCIAL_API_URL}?action=fetchPrivacyStatus`,

    fetchBuddyReads:`${SOCIAL_API_URL}?action=fetchBuddyReads`,
    createBuddyRead:`${SOCIAL_API_URL}?action=createBuddyRead`,
    fetchBuddyReadDetails:`${SOCIAL_API_URL}?action=fetchBuddyReadDetails`,
    submitComment:`${SOCIAL_API_URL}?action=submitComment`,
    fetchComments:`${SOCIAL_API_URL}?action=fetchComments`,
    fetchReplies:`${SOCIAL_API_URL}?action=fetchReplies`,
    deleteComment:`${SOCIAL_API_URL}?action=deleteComment`,
    toggleLike:`${SOCIAL_API_URL}?action=toggleLike`,
    JoinLeaveBuddyReads:`${SOCIAL_API_URL}?action=JoinLeaveBuddyReads`,
    updateBuddyReadDescription:`${SOCIAL_API_URL}?action=updateBuddyReadDescription`,

    createReadalong:`${SOCIAL_API_URL}?action=createReadalong`,
    fetchReadalongs:`${SOCIAL_API_URL}?action=fetchReadalongs`,
    fetchReadalongDetails:`${SOCIAL_API_URL}?action=fetchReadalongDetails`,
    checkReadalongMembership:`${SOCIAL_API_URL}?action=checkReadalongMembership`,
    updateReadalongDescription:`${SOCIAL_API_URL}?action=updateReadalongDescription`,
    JoinLeaveReadalongs:`${SOCIAL_API_URL}?action=JoinLeaveReadalongs`,
    fetchReadalongComments:`${SOCIAL_API_URL}?action=fetchReadalongComments`,
    submitReadalongComment:`${SOCIAL_API_URL}?action=submitReadalongComment`,
    toggleReadalongLike:`${SOCIAL_API_URL}?action=toggleReadalongLike`,
    deleteReadalongComment:`${SOCIAL_API_URL}?action=deleteReadalongComment`,
    createOrUpdateReadalongCheckpoints:`${SOCIAL_API_URL}?action=createOrUpdateReadalongCheckpoints`,
    fetchreadalongCheckpoints:`${SOCIAL_API_URL}?action=fetchreadalongCheckpoints`,
    
    fetchBookClubs:`${SOCIAL_API_URL}?action=fetchBookClubs`,
    createBookClub:`${SOCIAL_API_URL}?action=createBookClub`,
    fetchBookClubDetails:`${SOCIAL_API_URL}?action=fetchBookClubDetails`,
    checkBookClubMembership:`${SOCIAL_API_URL}?action=checkBookClubMembership`,
    updateBookClubDescription:`${SOCIAL_API_URL}?action=updateBookClubDescription`,
    JoinLeaveBookClub:`${SOCIAL_API_URL}?action=JoinLeaveBookClub`,
    fetchBookClubMeetings:`${SOCIAL_API_URL}?action=fetchBookClubMeetings`,
    updateBookClubCode:`${SOCIAL_API_URL}?action=updateBookClubCode`,
    updateBookClubAbout:`${SOCIAL_API_URL}?action=updateBookClubAbout`,
    createOrUpdateBookClubMeetings:`${SOCIAL_API_URL}?action=createOrUpdateBookClubMeetings`,

    fetchSimilarUsers:`${SOCIAL_API_URL}?action=fetchSimilarUsers`,

    //request to biblophile challenges apis
    createChallenge:`${CHALLENGES_API_URL}?action=createChallenge`,
    JoinLeaveChallenge:`${CHALLENGES_API_URL}?action=JoinLeaveChallenge`,
    fetchChallenges:`${CHALLENGES_API_URL}?action=fetchChallenges`,
    fetchChallengeDetails:`${CHALLENGES_API_URL}?action=fetchChallengeDetails`,
    checkChallengeHost:`${CHALLENGES_API_URL}?action=checkChallengeHost`,
    checkChallengeMembership:`${CHALLENGES_API_URL}?action=checkChallengeMembership`,
    updateChallengeDescription:`${CHALLENGES_API_URL}?action=updateChallengeDescription`,
    fetchChallengePrompts:`${CHALLENGES_API_URL}?action=fetchChallengePrompts`,
    createOrUpdateChallengePrompts:`${CHALLENGES_API_URL}?action=createOrUpdateChallengePrompts`,
    fetchPromptDetails:`${CHALLENGES_API_URL}?action=fetchPromptDetails`,
    updatePromptProgress:`${CHALLENGES_API_URL}?action=updatePromptProgress`,

}

export default requests;