const isDevelopment = __DEV__;

const APIURL = isDevelopment ? '/actions.php' : '/actions1.php';

const requests = {
    //request to biblophile actions api
    getBookGenre:`${APIURL}?action=getBookGenre`,
    getBooks:`${APIURL}?action=getBooks&bookGenre=`,
    fetchProductDetails:`${APIURL}?action=fetchProductDetails&id=`,
    fetchExternalBookDetails:`${APIURL}?action=fetchExternalBookDetails&id=`, 
    fetchAverageRating:`${APIURL}?action=fetchAverageRating&id=`,
    fetchAverageEmotions:`${APIURL}?action=fetchAverageEmotions&id=`,
    addBook: `${APIURL}?action=addBook`,
    fetchBookId:`${APIURL}?action=fetchBookId`,
    fetchReadingStatus:`${APIURL}?action=fetchReadingStatus`,
    submitReadingStatus: `${APIURL}?action=submitReadingStatus`,
    fetchProductReviews:`${APIURL}?action=fetchProductReviews&id=`,
    fetchEmotions:`${APIURL}?action=fetchEmotions`,
    submitReview: `${APIURL}?action=submitReview`,
    submitNote: `${APIURL}?action=submitNote`,
    submitEmotionScore: `${APIURL}?action=submitEmotionScore`,
    placeOrder: `${APIURL}?action=placeOrder`,
    placeSubscriptionOrder: `${APIURL}?action=placeSubscriptionOrder`,
    userLogin: `${APIURL}?action=userLogin`,
    userSignup: `${APIURL}?action=userSignup`,
    forgotPassword: `${APIURL}?action=forgotPassword`,
    fetchUserData: `${APIURL}?action=fetchUserData`,
    fetchOrders: `${APIURL}?action=fetchOrders`,
    updateUserData: `${APIURL}?action=updateUserData`,
    updateAppUserData: `${APIURL}?action=updateAppUserData`,
    fetchDeposit: `${APIURL}?action=fetchDeposit`,
    searchBooks: `${APIURL}?action=searchBooks&searchQuery=`,
    searchExternalBooks: `${APIURL}?action=searchExternalBooks&searchQuery=`,
    fetchSubscriptionPlans: `${APIURL}?action=fetchSubscriptionPlans`,
    fetchActivePlan: `${APIURL}?action=fetchActivePlan&userId=`,
    getBookmarks: `${APIURL}?action=getBookmarks`,
    fetchReadingStreak: `${APIURL}?action=fetchReadingStreak&userId=`,
    updateReadingStreak: `${APIURL}?action=updateReadingStreak&userId=`,
    updatePagesRead: `${APIURL}?action=updatePagesRead`,
    fetchReadingTips: `${APIURL}?action=fetchReadingTips`,
    updateNotificationToken: `${APIURL}?action=updateNotificationToken`,
    fetchReadingStreakLeaderboard: `${APIURL}?action=fetchReadingStreakLeaderboard&userId=`,
    fetchPagesRead: `${APIURL}?action=fetchPagesRead&userId=`,
    fetchCurrentReads: `${APIURL}?action=fetchCurrentReads`,
    fetchUserBooks: `${APIURL}?action=fetchUserBooks`,
    updateBookDates: `${APIURL}?action=updateBookDates`,
    paymentRequest: `${APIURL}?action=paymentRequest`,
    paymentSuccessful: `${APIURL}?action=paymentSuccessful&linkId=`,

    //request to biblophile user-insights api
    fetchAverageRatingByUser:`/userInsights.php?action=fetchAverageRatingByUser&userId=`,
    fetchAverageEmotionsByUser:`/userInsights.php?action=fetchAverageEmotionsByUser&userId=`,
    fetchAverageDaystoFinish: `/userInsights.php?action=fetchAverageDaystoFinish&userId=`,
    fetchUserReviews: `/userInsights.php?action=fetchUserReviews&userId=`,
    updateUserReview: `/userInsights.php?action=updateUserReview`,
    fetchBookShelf: `/userInsights.php?action=fetchBookShelf`,
    fetchUserNotes: `/userInsights.php?action=fetchUserNotes&userId=`,
    updateUserNote: `/userInsights.php?action=updateUserNote`,
}

export default requests;