const requests = {
    //request to biblophile actions api
    getBookGenre:`/actions1.php?action=getBookGenre`,
    getBooks:`/actions1.php?action=getBooks&bookGenre=`,
    placeOrder: `/actions1.php?action=placeOrder`,
    placeSubscriptionOrder: `/actions1.php?action=placeSubscriptionOrder`,
    userLogin: `/actions1.php?action=userLogin`,
    userSignup: `/actions1.php?action=userSignup`,
    forgotPassword: `/actions1.php?action=forgotPassword`,
    fetchUserData: `/actions1.php?action=fetchUserData`,
    fetchOrders: `/actions1.php?action=fetchOrders`,
    updateUserData: `/actions1.php?action=updateUserData`,
    updateAppUserData: `/actions1.php?action=updateAppUserData`,
    fetchDeposit: `/actions1.php?action=fetchDeposit`,
    searchBooks: `/actions1.php?action=searchBooks&searchQuery=`,
    fetchSubscriptionPlans: `/actions1.php?action=fetchSubscriptionPlans`,
    fetchActivePlan: `/actions1.php?action=fetchActivePlan&userId=`,
    getBookmarks: `/actions1.php?action=getBookmarks`,
    fetchReadingStreak: `/actions1.php?action=fetchReadingStreak&userId=`,
    updateReadingStreak: `/actions1.php?action=updateReadingStreak&userId=`,
    updatePagesRead: `/actions1.php?action=updatePagesRead&userId=`,
    fetchReadingTips: `/actions1.php?action=fetchReadingTips`,
    updateNotificationToken: `/actions1.php?action=updateNotificationToken`,
    fetchReadingStreakLeaderboard: `/actions1.php?action=fetchReadingStreakLeaderboard&userId=`,
    fetchPagesRead: `/actions1.php?action=fetchPagesRead&userId=`,
    paymentRequest: `/actions1.php?action=paymentRequest`,
    paymentSuccessful: `/actions1.php?action=paymentSuccessful&linkId=`,
}

export default requests;